### PR TITLE
Minor Bug fix & add .gitignore.

### PR DESCRIPTION
**Pull request by epinapala**
- Add .gitignore for the backend, frontend directories to recursively ignore unneeded directories/files.

- Fix an issue where an improper empty check for URL results in an exception. Use isNull vs isEmpty to avoid this issue.

### CODE REVIEW

**Comment by epinapala** [comment]
@jasperblues can you please take a look?

**Comment by jasperblues** [comment]
Thanks a lot @epinapala - sorry for the delay!

**Comment by epinapala** [comment]
Thanks @jasperblues for helping me understand the problem at kotlinconf.

**Comment by jasperblues** [comment]
@epinapala I think it was most likely the legendary @jexp who you spoke to at the conference! 
_(I would have loved to be there in person, but couldn't make it this year)._

**Pull request merged**
